FROM continuumio/miniconda3:latest

WORKDIR /app

RUN conda install -c conda-forge pythonocc-core -y

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
